name: Generate Plugin Zip

on:
    workflow_call:
        inputs:
            ref:
                description: 'Git Commit Ref (branch, tag, or hash)'
                required: true
                type: string
            plugin_slug:
                description: 'Plugin Slug'
                required: true
                type: string
            install_composer_packages:
                description: 'Whether composer needs to be run as part of the build'
                type: boolean
                required: false
                default: true
            install_npm_packages:
                description: 'Whether NPM needs to be run as part of the build'
                type: boolean
                required: false
                default: true

jobs:
    generate-zip:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ inputs.ref }}
                    plugin_slug: better-click-to-tweet

            -   name: Install composer dependencies
                uses: php-actions/composer@v6
                if: ${{ inputs.install_composer_packages }}
                with:
                    php_version: 7.4
                    dev: no

            -   uses: actions/setup-node@v3
                with:
                    node-version: '12'

            -   name: Install npm dependencies & build for translation
                if: ${{ inputs.install_npm_packages }}
                run: |
                    npm install -g npm@7
                    npm ci
                    npm run build
            -   name: Generate pot file
                run: |
                    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
                    chmod +x wp-cli.phar
                    mv wp-cli.phar /usr/local/bin/wp
                    php -d xdebug.mode=off "$(which wp)" i18n make-pot ${{github.workspace}} ${{github.workspace}}/languages/${{ inputs.plugin_slug }}.pot --exclude="$(cat .distignore | tr "\n" "," | sed 's/,$/ /' | tr " " "\n"),src/*.js,src/**/*.js,blocks/**/*.js"
            -   uses: impress-org/givewp-github-actions/.github/actions/generate-changelog@master

            -   name: Generate plugin zip file
                run: rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "${GITHUB_WORKSPACE}/" ${{ inputs.plugin_slug }}/ --delete --delete-excluded

            -   name: Upload plugin artifact
                uses: actions/upload-artifact@v3
                with:
                    name: ${{ inputs.plugin_slug }}
                    path: ${{ inputs.plugin_slug }}
